  
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: RUN - BUILD & TEST

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2 
    
    - name: Install modules
      run: |
        cd ./NewsBackend
        npm install
    
    - name: BUILD
      run: |
        cd ./NewsBackend
        npm build
    
    - name: TEST
      run: |
        cd ./NewsBackend
        npm test
